### ISSUE TITLE
jsxTransform.js cannot find proxies.js

### ISSUE THREAD

**Issue by xhocquet** [geowarin/electron-hot-loader#7]
Seems like a pathing issue within the module.

Full Error:

```
project\node_modules\electron-hot-loader\src\jsxTransform.js:67
 Uncaught Error: Error compiling project\scripts\modules\trackList.jsx: Cannot find module 'projectode_moduleselectron-hot-loadersrcproxies.js'
```

Looks like that last path, `\n` in `project\node_modules` was turned into a new line.
This is on a windows machine.

**Comment by geowarin** [comment]
Never tested it on windows!
Do the tests of the project pass on your machine?

**Comment by geowarin** [comment]
I used appveyor to run the tests on windows.

There was a small error related to a buggy regexp in the testing code. 
Otherwise, everything seems to [run smoothly on windows](https://ci.appveyor.com/project/geowarin/electron-hot-loader).

I know this is a lot to ask but I would be awesome if you could come up with a failing test for this!

**Comment by geowarin** [comment]
Ok I guess it might be [simpler](https://github.com/geowarin/electron-hot-loader/commit/8e68c94f99410dbb125a1012c020fd86bbc61796) than I thought.
Could you try again by replacing electron-hot-loader version by `geowarin/electron-hot-loader` in your package.json to test the master branch.

If that works, I'll publish a new version tomorrow.

**Comment by xhocquet** [comment]
Trying it out now!

**Comment by xhocquet** [comment]
Just ran `npm install` after cloning master:

```

  jsxTransform
    √ should transform a JSX file without instrumenting it (96ms)
    1) should transform a JSX file and instrument it
    2) should transform a JSX file, instrument it and keep the source map
    3) should transform and instrument React top level render
    4) should transform and instrument higher order components
    5) should instrument higher order components in the same file
    6) should not instrument components in node_modules
```

Last 6 are failing here.

**Comment by xhocquet** [comment]
They're all failing on this:

```
 + expected - actual

       "use strict";
       const connect = require('react-redux').connect;
      -var __electronHot__ = require('D:/Coding/electron-hot-loader/src/proxies.js');
      +var __electronHot__ = require('D:\Coding\electron-hot-loader\src\proxies.js');
```

So yeah, looks like forward slashes are being changed to backslashes

**Comment by xhocquet** [comment]
The link you provided above with the tests shows the same thing as my machine, 6/7 failed.

**Comment by geowarin** [comment]
Yeah I kind of broke the windows build it with my last commit.

In short.
Electron-hot relies on `require.resolve` in several locations to find files.
Those files are either the lib itself, or the components that need hot reloading.

Replacing backslashes with slashes should fix the problem.

I just pushed a new version if you want to test but I guess I really need a good test to secure this.
I will look at it tomorrow more seriously.

**Comment by xhocquet** [comment]
Same tests are failing on my machine, though the test results show that it should be passing, unless I'm missing something:

```
  4) jsxTransform should transform and instrument higher order components:

      Error: Expected '"use strict";\r\nconst connect = require(\'react-redux\').connect;\r\nvar __electronHot__ = require(\'D:/Coding/electron-hot-loader/src/proxies.js\');\nconst Component = require(\'./Component.jsx\');\r\n\r\nmodule.exports = connect(\r\n    (state) => ({counter: state.counter})\r\n)(__electronHot__.register(Component, require.resolve(\'./Component.jsx\')));\r\n' to equal '"use strict";\r\nconst connect = require(\'react-redux\').connect;\r\nvar __electronHot__ = require(\'D:/Coding/electron-hot-loader/src/proxies.js\');\r\nconst Component = require(\'./Component.jsx\');\r\n\r\nmodule.exports = connect(\r\n    (state) => ({counter: state.counter})\r\n)(__electronHot__.register(Component, require.resolve(\'./Component.jsx\')));\r\n'
      + expected - actual

       "use strict";
       const connect = require('react-redux').connect;
      -var __electronHot__ = require('D:/Coding/electron-hot-loader/src/proxies.js');
      +var __electronHot__ = require('D:/Coding/electron-hot-loader/src/proxies.js');
       const Component = require('./Component.jsx');

       module.exports = connect(
           (state) => ({counter: state.counter})

      at assert (D:\Coding\electron-hot-loader\node_modules\expect\lib\assert.js:22:9)
```

**Comment by geowarin** [comment]
I believe I solved the problem in #8.
One build passes and the other fails on appveyor, I have no idea why.

@xhocquet, could you please give it a try by putting:

``` json
dependencies {
    "electron-hot-loader": "geowarin/electron-hot-loader#fix-windows-paths"
}
```

In your `package.json` and doing another `npm install`?

If the problem is solved for you, I'll merge this and release a new version.
Thanks!

**Comment by xhocquet** [comment]
Ive just been working in the module only, not trying new stuff out in my app.

On `fix-windows-paths`, the same errors persist.

**Comment by xhocquet** [comment]
Although looks like new tests are passing:

```
  loadJsx
    √ should throw when a component contains an error (83ms)
    √ should throw a simple error when a component contains a component which contains an error (377ms)

  jsxTransform
    √ should transform a JSX file without instrumenting it
    1) should transform a JSX file and instrument it
    2) should transform a JSX file, instrument it and keep the source map
    3) should transform and instrument React top level render
    4) should transform and instrument higher order components
    5) should instrument higher order components in the same file
    6) should not instrument components in node_modules
```

**Comment by geowarin** [comment]
What about `npm run test:integ`?

**Comment by xhocquet** [comment]
```
npm run test:integ

> electron-hot-loader@0.6.1 test:integ D:\Coding\electron-hot-loader
> mocha --opts test-integration/mocha.opts

module.js:341
    throw err;
    ^

Error: Cannot find module 'temp'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\Coding\electron-hot-loader\test-integration\hot-reload.spec.jsx:9:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at D:\Coding\electron-hot-loader\node_modules\mocha\lib\mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (D:\Coding\electron-hot-loader\node_modules\mocha\lib\mocha.js:216:14)
    at Mocha.run (D:\Coding\electron-hot-loader\node_modules\mocha\lib\mocha.js:468:10)
    at Object.<anonymous> (D:\Coding\electron-hot-loader\node_modules\mocha\bin\_mocha:403:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by geowarin** [comment]
Yeah I added a lib to generate temp folders, you have to `npm install` again

**Comment by xhocquet** [comment]
Duh! `npm run test:integ` finished without errors, regular `npm test` still doesn't

**Comment by geowarin** [comment]
Ok. I have a windows machine at work so I gave it a try.
This is pretty weird.
Depending on which shell I use, it breaks.

## With git-bash:

Tests are broken.
I have diffs that do not really make sense:

``` diff
 -var __electronHot__ = require('d:/Temp/electron-hot-loader/src/proxies.js');
 +var __electronHot__ = require('d:/Temp/electron-hot-loader/src/proxies.js');
  const React = require('react');
  const OtherComponent = require('external-lib/OtherComponent');
```

The integration test does not work because watch-glob does not pick up the changes.

With `electron-hot-boilerplate` changes are not picked up by watch-glob just like the integration test.
**But I have no errors in the paths so the initial problem is fixed**.

## With cmd

Everything works... :confused:

**Comment by xhocquet** [comment]
Interesting, I'm just using cmd but I have git bundled into it, probably same as git-bash.

**Comment by geowarin** [comment]
Ok the diffs are obviously CRLF vs LF.
And the integration test actually randomly breaks.

I guess watch-glob just takes more time to detect changes.
I'll fix this by increasing the timeout on windows machines.

In the meantime, I do believe the problem **is fixed**.
I just tested again with git-bash and electron-hot-boilerplate works.

Thanks again for your time, you've been really reactive.
Could you give it a final try in your project, making sure you delete your `node_modules` and pointing to the `geowarin/electron-hot-loader#fix-windows-paths` branch.`

This will effectively fetch the module [from github](https://docs.npmjs.com/files/package.json#github-urls) instead of npm.

Forget about the tests, failures are just windows line breaks shenanigans.

**Comment by xhocquet** [comment]
Yep, looks like that error disappeared and the library is functioning. Thanks!

**Comment by geowarin** [comment]
Fixed in [v0.7.0](https://github.com/geowarin/electron-hot-loader/releases/tag/v0.7.0).
Thanks for submitting the issue.
